name: Update dxpr/dxpr_theme docker image

on:
  push:
    branches:
      - '5.x'
      - '6.x'
      - '8.x'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Set branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            PHP_TAG=8.1-dev-4.53.0
            DXPR_THEME_CONTAINER=/usr/src/dxpr_theme
          push: true
          tags: dxpr/dxpr_theme:${{ steps.branch.outputs.BRANCH_NAME }}
