name: Review

on: [pull_request]

env:
  TARGET_DRUPAL_CORE_VERSION: 11

jobs:
  drupal-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4

    - name: Lint Drupal
      run: |
        docker compose --profile lint run drupal-lint

  drupal-check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4

    - name: Check Drupal compatibility
      run: |
        docker compose --profile lint run drupal-check
